# From https://github.com/DanySK/Gravis-CI

language: bash
dist: xenial
os:
  - linux

env:
  global:
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"

  matrix:
    # List any JDK you want to build your software with.
    # You can see the list of supported environments by installing Jabba and using ls-remote:
    # https://github.com/shyiko/jabba#usage
    - JDK="openjdk-ri@1.7.75"
    - JDK="adopt@1.8.0-232"
    - JDK="openjdk@1.9.0-4"
    - JDK="1.12.0-1"
    - JDK="1.13.0"

cache:
  directories:
    # Avoid re-downloading the JDK every time
    - $HOME/.jabba/
    - $HOME/.m2/

before_install:
  # Sets up the Java environment
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  # Get maven 3.1.1
  - "wget http://apache.mirror.iphh.net/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz && tar xfz apache-maven-3.1.1-bin.tar.gz && sudo mv apache-maven-3.1.1 /usr/local/maven-3.1.1 && sudo rm -f /usr/local/maven && sudo ln -s /usr/local/maven-3.1.1 /usr/local/maven"

before_script:
  - bash .install-jdk-travis.sh

script:
  - /usr/local/maven/bin/mvn verify -B
