# From https://github.com/DanySK/Gravis-CI

language: bash
dist: xenial
os:
  - linux

env:
  global:
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"

  matrix:
    # List any JDK you want to build your software with.
    # You can see the list of supported environments by installing Jabba and using ls-remote:
    # https://github.com/shyiko/jabba#usage
    - JDK="openjdk-ri@1.7.75"
    - JDK="adopt@1.8.212-04"
    - JDK="amazon-corretto@1.8.212-04.2"
    - JDK="openjdk@1.9.0-4"
    - JDK="1.12.0-1"

cache:
  directories:
    # Avoid re-downloading the JDK every time
    - $HOME/.jabba/
    - $HOME/.m2/

before_install:
  # Sets up the Java environment
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh

before_script:
  - bash .install-jdk-travis.sh

script:
  - mvn verify -B
