/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 16 22:11:41 GMT 2018
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Node;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataNode_ESTest extends DataNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DataNode dataNode0 = new DataNode("tZ");
      dataNode0.outerHtmlTail((Appendable) null, 2094, (Document.OutputSettings) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("", "#data");
      dataNode0.toString();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DataNode dataNode0 = new DataNode("", "");
      dataNode0.setSiblingIndex(2585);
      dataNode0.setWholeData("");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DataNode dataNode0 = new DataNode("N;8Dl_{Q@qRk>Lt", "");
      dataNode0.setSiblingIndex((-235));
      dataNode0.setWholeData("8EXl8GDr");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DataNode dataNode0 = new DataNode("NEd", "");
      dataNode0.reparentChild(dataNode0);
      dataNode0.setWholeData("");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DataNode dataNode0 = new DataNode((String) null);
      dataNode0.getWholeData();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DataNode dataNode0 = new DataNode("", "");
      dataNode0.setParentNode(dataNode0);
      // Undeclared exception!
      dataNode0.toString();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DataNode dataNode0 = new DataNode("org.jsoup.nodes.DataNode", "");
      dataNode0.clearAttributes();
      dataNode0.parentNode = (Node) dataNode0;
      // Undeclared exception!
      dataNode0.setWholeData("");
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DataNode dataNode0 = new DataNode("VD;[R8$q", "VD;[R8$q");
      // Undeclared exception!
      try { 
        dataNode0.outerHtmlHead((Appendable) null, 2013, (Document.OutputSettings) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.DataNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        DataNode.createFromEncoded((String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DataNode dataNode0 = new DataNode("qs4OAPIHOf%T");
      dataNode0.nodeName();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DataNode dataNode0 = new DataNode("tZ");
      dataNode0.getWholeData();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DataNode dataNode0 = new DataNode("N;8Dl_{Q@qRk>Lt", "N;8Dl_{Q@qRk>Lt");
      dataNode0.toString();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DataNode dataNode0 = new DataNode("", "");
      dataNode0.getWholeData();
      assertEquals("#data", dataNode0.nodeName());
  }
}
