/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 07 22:08:51 GMT 2018
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.jsoup.SerializationException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SerializationException_ESTest extends SerializationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("");
      SerializationException serializationException0 = new SerializationException(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SerializationException serializationException0 = new SerializationException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SerializationException serializationException0 = new SerializationException("zLlg)ziioyMGvP");
      SerializationException serializationException1 = new SerializationException("", serializationException0);
      assertFalse(serializationException1.equals((Object)serializationException0));
  }
}
