package org.jsoup.select;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 Tests for ElementList.

 @author Jonathan Hedley, jonathan@hedley.net */
public class ElementsTest {
    @Test public void chainedSelects() {
        String h = "<p>Excl</p><div class=headline><p>Hello</p><p>There</p></div><div class=headline><h1>Headline</h1></div>";
        Document doc = Jsoup.parse(h);
        Elements els = doc.select(".headline").select("p");
        assertEquals(2, els.size());
        assertEquals("Hello", els.get(0).text());
        assertEquals("There", els.get(1).text());
    }

    @Test public void play() {
        String h = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\n"
                + "<head>\n"
                + "    <title>Financial crisis</title>\n"
                + "    <meta http-equiv=\"content-language\" content=\"en\" />\n"
                + "<meta http-equiv=\"imagetoolbar\" content=\"no\" />\n"
                + "<meta name=\"robots\" content=\"noarchive,noodp\" />\n"
                + "<meta name=\"robots\" content=\"ACAP allow-index\" />\n"
                + "<meta name=\"robots\" content=\"ACAP allow-follow\" />\n"
                + "<meta name=\"robots\" content=\"ACAP disallow-preserve\" />\n"
                + "<meta name=\"robots\" content=\"ACAP allow-present prohibited-modification=annotation\" />\n"
                + "<meta name=\"description\" content=\"\" />\n"
                + "<meta name=\"keywords\" content=\"\" />\n"
                + "\n"
                + "    \n"
                + "\n"
                + "<!-- Styles =================================================================== -->\n"
                + "<!-- Have these styles for both screen and print to create a base for printing: -->\n"
                + "<link rel=\"stylesheet\" type=\"text/css\" media=\"screen,print\" href=\"http://resources.smh.com.au/common/media-common-1.0/css/base.css\" />\n"
                + "<!-- Skin CSS: -->\n"
                + "<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\"       href=\"http://resources.smh.com.au/common/media-common-1.0/css/base-skin-news/skin-news.css\" />\n"
                + "<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\"       href=\"http://resources.smh.com.au/common/media-common-1.0/css/skin-business/skin-business.css\" />\n"
                + "    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"http://resources.smh.com.au/common/media-common-1.0/css/skin-promotions/skin-promotions.css\" />\n"
                + "<link rel=\"alternate stylesheet\" type=\"text/css\" media=\"screen\" title=\"High contrast\" href=\"http://resources.smh.com.au/common/media-common-1.0/css/base-skin-news/skin-news-low-vision.css\" />\n"
                + "<!-- Any adjustments we need to do for handheld devices: -->\n"
                + "<link rel=\"stylesheet\" type=\"text/css\" media=\"handheld\"     href=\"http://resources.smh.com.au/common/media-common-1.0/css/mobile.css\" />\n"
                + "\n"
                + "<script type=\"text/javascript\" >\n"
                + "    var delayedAds = [];\n"
                + "</script>\n"
                + "\n"
                + "\n"
                + "\n"
                + "    <!-- All Javascript calls go here, after the content so loading and parsing a script does not affect content loading: -->\n"
                + "    <script type=\"text/javascript\" src=\"http://resources.smh.com.au/common/media-common-1.0/js/fd.mt.media.com.au.js\"></script>\n"
                + "<script type=\"text/javascript\" src=\"http://resources.smh.com.au/common/media-common-1.0/js/fd.media.custom.js\"></script>\n"
                + "<script type=\"text/javascript\" src=\"http://resources.smh.com.au/common/media-common-1.0/js/adParams.js\"></script>\n"
                + "<script type=\"text/javascript\" src=\"http://resources.smh.com.au/common/media-common-1.0/js/europa.lite.packed.js\"></script>\n"
                + "\n"
                + "<script type=\"text/javascript\">\n"
                + "\n"
                + "    function initPreAdLoadImage() {\n"
                + "        new Element(\"img\", {\n"
                + "            width: 1,\n"
                + "            height: 1,\n"
                + "            src: \"http://direct.fairfax.com.au/vserver/CCID=1/AREA=BUSINESS.SMH.BUSINESS.PRINT/BT=1/ACC_RANDOM=998260\",\n"
                + "            styles: {\n"
                + "                display: 'none'\n"
                + "            }\n"
                + "        });\n"
                + "    }\n"
                + "\n"
                + "    FD.register(\"PreAdLoadImage\");\n"
                + "\n"
                + "    var siteAdvertDesc = {\n"
                + "        redir: \"/adredirect.html?ad=\"\n"
                + "    };\n"
                + "\n"
                + "       \n"
                + "    FD.baseAd = {\n"
                + "        src: \t\"http://direct.fairfax.com.au/jserver/\",        \n"
                + "        params: {\n"
                + "            cat: \"BUSINESS\",\n"
                + "            site: \"ONL.MH.SMH.BUSINESS\",\n"
                + "            ctype: \"ARTICLE\",\n"
                + "            area: \"BUSINESS.SMH.BUSINESS.PRINT\",\n"
                + "            cat1: \"PRINT\",\n"
                + "        isiframe: \"yes\"\n"
                + "        }\n"
                + "    };\n"
                + "\n"
                + "    function initPost() {\n"
                + "\n"
                + "\n"
                + "        try {\n"
                + "            document.domain = \"smh.com.au\";\n"
                + "        }\n"
                + "        catch (e)\n"
                + "        {\n"
                + "            // if working dev the above will fail\n"
                + "        }\n"
                + "\n"
                + "        for(var i = 0; i < delayedAds.length; i++) {\n"
                + "            delayedAds[i]();\n"
                + "        }\n"
                + "    }\n"
                + "</script>\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body class=\"smh business\">\n"
                + "<script type=\"text/javascript\">\n"
                + "// <![CDATA[\n"
                + "\tdocument.body.className += \" scriptable\";\n"
                + "// ]]>\n"
                + "</script>\n"
                + "\n"
                + "\n"
                + "<a class=\"skipLink\" href=\"#nav\">Skip to navigation</a>\n"
                + "<a class=\"skipLink\" href=\"#content\">Skip to content</a>\n"
                + "\n"
                + "<div class=\"wrap cfix\">\n"
                + "\n"
                + "    <div id=\"adspot-1x10\" class=\"\"></div>\n"
                + "\n"
                + "<script type=\"text/javascript\">\n"
                + "\n"
                + "    delayedAds.push(function(){\n"
                + "        FD.addAd($merge(FD.baseAd, {\n"
                + "            id: \"adspot-1x10\",\n"
                + "            iframeId: \"adspot-1x10-iframe\",\n"
                + "            params: $merge($merge(FD.baseAd.params, {\n"
                + "                aamsz : \"1x10\"\n"
                + "        }),getAdParams(\"1x10\"))\n"
                + "\n"
                + "            ,height: 1\n"
                + "            ,width: 1\n"
                + "            })\n"
                + "        );\n"
                + "    }\n"
                + ");\n"
                + "\n"
                + "</script>\n"
                + "\n"
                + "    \n"
                + "<!-- Network strip top (scope: network-wide) -->\n"
                + "<div class=\"nN-whiteStrip\">\n"
                + "    <a class=\"logo\" href=\"http://www.fairfaxdigital.com.au/\" onclick=\"linktop(this);\">Fairfax Digital</a>\n"
                + "    <ul class=\"links\">\n"
                + "        <li><a href=\"http://newsbreak.com.au/\" onclick=\"linktop(this);\">News</a></li>\n"
                + "        <li><a href=\"http://mycareer.com.au/\" onclick=\"linktop(this);\">MyCareer</a></li>\n"
                + "        <li><a href=\"http://www.domain.com.au/\" onclick=\"linktop(this);\">Domain</a></li>\n"
                + "        <li><a href=\"http://www.drive.com.au/\" onclick=\"linktop(this);\">Drive</a></li>\n"
                + "        <li><a href=\"http://businessday.com.au/\" onclick=\"linktop(this);\">Finance</a></li>\n"
                + "        <li><a href=\"http://mobile.fairfax.com.au/\" onclick=\"linktop(this);\">Mobile</a></li>\n"
                + "        <li><a href=\"http://www.rsvp.com.au/\" onclick=\"linktop(this);\">RSVP</a></li>\n"
                + "        <li><a href=\"http://www.smh.com.au/travel/travel-landing/\" onclick=\"linktop(this);\">Travel</a></li>\n"
                + "        <li class=\"last\"><a href=\"http://www.weatherzone.com.au/\" onclick=\"linktop(this);\">Weather</a></li>\n"
                + "    </ul>\n"
                + "    <ul class=\"memberCentre\">\n"
                + "        <li><a href=\"http://www.fairfax.com.au/map/\" onclick=\"linktop(this);\">network map</a></li><li class=\"last\"><a href=\"http://fairfaxdigital.com.au/\" onclick=\"linktop(this);\">member centre</a></li>\n"
                + "    </ul>\n"
                + "</div>\n"
                + "<!-- End component: Network strip top -->\n"
                + "\n"
                + "\n"
                + "<!-- Header (class according to new HTML5 element 'header'; was 'masthead') (scope: network-wide) -->\n"
                + "<div class=\"header span-24\">\n"
                + "    <div id=\"adspot-468X60-pos-1\" class=\"ad\"></div>\n"
                + "\n"
                + "<script type=\"text/javascript\">\n"
                + "\n"
                + "    delayedAds.push(function(){\n"
                + "        FD.addAd($merge(FD.baseAd, {\n"
                + "            id: \"adspot-468X60-pos-1\",\n"
                + "            iframeId: \"adspot-468X60-pos-1-iframe\",\n"
                + "            params: $merge($merge(FD.baseAd.params, {\n"
                + "                    pos: 1,\n"
                + "                    adtype: 'panorama',\n"
                + "                aamsz : \"468X60\"\n"
                + "        }),getAdParams(\"468X60\"))\n"
                + "\n"
                + "            })\n"
                + "        );\n"
                + "    }\n"
                + ");\n"
                + "\n"
                + "</script>\n"
                + "    <p class=\"mh-logo\"><a href=\"http://www.smh.com.au\" title=\"The Sydney Morning Herald\">The Sydney Morning Herald</a></p>\n"
                + "            <h2><a href=\"http://business.smh.com.au\" title=\"Business\">Business</a></h2>\n"
                + "\n"
                + "        <!-- Navigation (scope: network-wide) -->\n"
                + "    <ul id=\"nav\" class=\"hasSubNav\">\n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li class=\"selected\">\n"
                + "                    <a href=\"http://www.smh.com.au/business\" title=\"News\">News</a>\n"
                + "\n"
                + "                        <ol>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/business/national\" title=\"Today's News & Views\">Today's News & Views</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/business/opinion\" title=\"Comment & Analysis\">Comment & Analysis</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/business/world\" title=\"World Business\">World Business</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/business/marketing\" title=\"Media & Marketing\">Media & Marketing</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/business/print-edition\" title=\"Newspaper Edition\">Newspaper Edition</a>\n"
                + "                                </li>\n"
                + "                                <li class=\"last\">\n"
                + "                                    <a href=\"http://mobile.fairfax.com.au/\" title=\"BusinessDay Mobile\">BusinessDay Mobile</a>\n"
                + "                                </li>\n"
                + "                        </ol>\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li>\n"
                + "                    <a href=\"http://www.smh.com.au/business/markets\" title=\"Markets\">Markets</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li>\n"
                + "                    <a href=\"http://markets.smh.com.au/apps/qt/index.ac\" title=\"Quotes\">Quotes</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li>\n"
                + "                    <a href=\"http://markets.smh.com.au/apps/pf/index.ac\" title=\"Portfolio\">Portfolio</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li>\n"
                + "                    <a href=\"http://www.smh.com.au/business/money/\" title=\"Money\">Money</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li>\n"
                + "                    <a href=\"http://www.smh.com.au/business/property\" title=\"Property Focus\">Property Focus</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li class=\" hasDropdown startup\">\n"
                + "                    <a href=\"http://smallbusiness.smh.com.au/\" title=\"Small Business\">Small Business</a>\n"
                + "\n"
                + "\n"
                + "                        <ul>\n"
                + "                                <li class=\"first\">\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/startup\" title=\"Startup\">Startup</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/managing\" title=\"Managing\">Managing</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/franchising\" title=\"Franchising\">Franchising</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/trends\" title=\"Trends\">Trends</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/entrepreneur\" title=\"Entrepreneur\">Entrepreneur</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/marketing\" title=\"Marketing\">Marketing</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/finance\" title=\"Finance\">Finance</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/technology\" title=\"Technology\">Technology</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/resources\" title=\"Resources\">Resources</a>\n"
                + "                                </li>\n"
                + "                                <li class=\"last\">\n"
                + "                                    <a href=\"http://www.smh.com.au/small-business/coaching\" title=\"Coaching\">Coaching</a>\n"
                + "                                </li>\n"
                + "                        </ul>\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li class=\" hasDropdown \">\n"
                + "                    <a href=\"http://www.smh.com.au/business/executivestyle/\" title=\"Executive Style\">Executive Style</a>\n"
                + "\n"
                + "\n"
                + "                        <ul>\n"
                + "                                <li class=\"first\">\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/travel/\" title=\"Travel\">Travel</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/motors/\" title=\"Motors\">Motors</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/culture/\" title=\"Culture\">Culture</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/gadgets\" title=\"Gadgets\">Gadgets</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/luxury\" title=\"Luxury\">Luxury</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/management/\" title=\"Management\">Management</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/style/\" title=\"Style\">Style</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/top-drop\" title=\"Wine\">Wine</a>\n"
                + "                                </li>\n"
                + "                                <li class=\"last\">\n"
                + "                                    <a href=\"http://www.smh.com.au/executive-style/fitness\" title=\"Fitness\">Fitness</a>\n"
                + "                                </li>\n"
                + "                        </ul>\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li class=\" hasDropdown \">\n"
                + "                    <a href=\"#\" title=\"Compare & Save\">Compare & Save</a>\n"
                + "\n"
                + "\n"
                + "                        <ul>\n"
                + "                                <li class=\"first\">\n"
                + "                                    <a href=\"http://compare.smh.com.au/credit-cards\" title=\"Credit Cards\">Credit Cards</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://compare.smh.com.au/debit-cards\" title=\"Debit Cards\">Debit Cards</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://compare.smh.com.au/home-loans\" title=\"Home Loans\">Home Loans</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://compare.smh.com.au/personal-loans\" title=\"Personal Loans\">Personal Loans</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://compare.smh.com.au/car-loans\" title=\"Car Loans\">Car Loans</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://compare.smh.com.au/term-deposits\" title=\"Term Deposits\">Term Deposits</a>\n"
                + "                                </li>\n"
                + "                                <li>\n"
                + "                                    <a href=\"http://compare.smh.com.au/bank-accounts\" title=\"Bank Accounts\">Bank Accounts</a>\n"
                + "                                </li>\n"
                + "                                <li class=\"last\">\n"
                + "                                    <a href=\"http://compare.smh.com.au/savings-accounts\" title=\"Saving Accounts\">Saving Accounts</a>\n"
                + "                                </li>\n"
                + "                        </ul>\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li>\n"
                + "                    <a href=\"/business/clevel\" title=\"C-Level\">C-Level</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + " \n"
                + "\n"
                + "\n"
                + "\n"
                + "                <li class=\" sponsor-1\">\n"
                + "                    <a href=\"http://www.smh.com.au/national/cfdeducation\" title=\"Trader Insights\">Trader Insights</a>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                    </li>\n"
                + "                    \n"
                + "            \n"
                + "    </ul>\n"
                + "    <!-- End module Navigation -->\n"
                + "\n"
                + "\n"
                + "        <!-- Breadcrumb (scope: network-wide) -->\n"
                + "    <p class=\"breadcrumb\">\n"
                + "        <span>You are here:</span>\n"
                + "            <a href=\"http://www.smh.com.au\">Home</a>\n"
                + "            &raquo; <a href=\"http://www.smh.com.au/business\">BusinessDay</a>\n"
                + "            &raquo; <a href=\"http://www.smh.com.au/business/financial-crisis-may-yet-have-a-sting-in-its-tail-20100102-lmka.html\">Article</a>\n"
                + "    </p>\n"
                + "\n"
                + "\n"
                + "        <ul class=\"altFormats\">\n"
                + "            <li class=\"mobiles\">\n"
                + "                <a href=\"http://mobile.fairfax.com.au/\">Mobiles</a>\n"
                + "            </li>\n"
                + "            <li class=\"rss\">\n"
                + "                <a href=\"http://www.smh.com.au/rssheadlines\">RSS</a>\n"
                + "            </li>\n"
                + "            <li class=\"newsletters\">\n"
                + "                <a href=\"https://membercentre.fairfax.com.au/NewsletterSubscription.aspx\">Newsletters</a>\n"
                + "            </li>\n"
                + "        <li id=\"vision\" class=\"last\"><a href=\"#\">High contrast</a></li>\n"
                + "    </ul>\n"
                + "\n"
                + "    \n"
                + "        <!-- Search (scope:network-wide) -->\n"
                + "    <div class=\"cN-searchBox cfix\">\n"
                + "    <form action=\"http://www.smh.com.au/execute_search.html\" method=\"get\">\n"
                + "        <h2>Search smh:</h2>\n"
                + "        <label for=\"search\">\n"
                + "            <input type=\"text\" name=\"text\" id=\"search\" value='Search here...' onfocus=\"this.value='';\" />\n"
                + "        </label>\n"
                + "        <h3>Search in:</h3>\n"
                + "        <ul id=\"ddown\" class=\"ddown\">\n"
                + "            <li><a class=\"selected\" href=\"#\">Business</a>\n"
                + "                <div class=\"srch-wrap\">\n"
                + "\t\t\t\t\t<div></div>\n"
                + "                    <ul class=\"cfix\">\n"
                + "                            <li class=\"first\"><a href=\"#\">smh.com.au</a></li>\n"
                + "                            <li><a href=\"#\">Web</a></li>\n"
                + "                            <li><a href=\"#\">Business</a></li>\n"
                + "                    </ul>\n"
                + "                </div>\n"
                + "            </li>\n"
                + "        </ul>\n"
                + "        <input type=\"hidden\" name=\"ss\" value=\"Business\" />\n"
                + "        <input type=\"submit\" class=\"btnSubmit\" value=\"Search\" />\n"
                + "    </form>\n"
                + "    </div>\n"
                + "\n"
                + "\n"
                + "</div>\n"
                + "<!-- End component: Header -->\n"
                + "\n"
                + "    \n"
                + "\t\n"
                + "\t<div id=\"adspot-940X20-pos-1\" class=\"ad\"></div>\n"
                + "\n"
                + "<script type=\"text/javascript\">\n"
                + "\n"
                + "    delayedAds.push(function(){\n"
                + "        FD.addAd($merge(FD.baseAd, {\n"
                + "            id: \"adspot-940X20-pos-1\",\n"
                + "            iframeId: \"adspot-940X20-pos-1-iframe\",\n"
                + "            params: $merge($merge(FD.baseAd.params, {\n"
                + "                    pos: 1,\n"
                + "                    adtype: 'panorama',\n"
                + "                aamsz : \"940X20\"\n"
                + "        }),getAdParams(\"940X20\"))\n"
                + "\n"
                + "            ,height: 1\n"
                + "            ,width: 940\n"
                + "            })\n"
                + "        );\n"
                + "    }\n"
                + ");\n"
                + "\n"
                + "</script>\n"
                + "\n"
                + "    <!-- Content. We use an id here to be able to jump to this section. -->\n"
                + "    <div id=\"content\" class=\"span-16\">\n"
                + "\n"
                + "        <!-- cN-headingPage -->\n"
                + "        <h1 class=\"cN-headingPage prepend-5 span-11 last\"><HEADLINE>Financial crisis may yet have a sting in its tail</HEADLINE></h1>\n"
                + "\n"
                + "        <!-- Class 'push-0' just right-aligns the element so that the main content comes first. -->\n"
                + "        <div class=\"push-0 span-11 last\">\n"
                + "\n"
                + "            \n"
                + "<!-- cT-storyDetails -->\n"
                + "<div class=\"cT-storyDetails cfix\">\n"
                + "                <h5>DAVID POTTS</h5>\n"
                + "        <cite>January 3, 2010</cite>\n"
                + "</div>\n"
                + "\n"
                + "<div class=\"ad adSpot-textBox\" id=\"googleAds\"></div>\n"
                + "\n"
                + "<BOD>\n"
                + "    <div class=\"articleBody\">\n"
                + "                    <p>\n"
                + "                        <strong>2009 was not as bad as feared but 2010 may be worse, writes Personal Finance Editor David Potts.</strong>\n"
                + "                    </p>\n"
                + "            <p><base href=\"http://proof.smh.com.au/cgi-bin/IndexAssistant/action/\"><style> html,body { border: 0px; }</style></p>\n"
                + "            <p>THIS year will be a sweet spot for savers, investors and self-funded retirees \n"
                + "but a struggle for most other Australians.</p>\n"
                + "            <p>Joe and Jane Average will face higher electricity, gas, water and transport \n"
                + "charges, higher mortgage repayments and, if the global recovery eventuates, \n"
                + "rising petrol prices. And all this is before the effects of what is expected to \n"
                + "be a tough May budget begin to kick in.</p>\n"
                + "            <p>But at least jobs will be easier to find as the year unfolds and wage rises \n"
                + "will be a reality again.</p>\n"
                + "            <p>Even inflation will drop slightly, thanks to the stronger dollar cutting \n"
                + "import prices and, weather permitting, falling food prices.</p>\n"
                + "            <p>It seems hard to imagine how anybody could possibly be any worse off in 2010 \n"
                + "than last year but the sting from the global financial crisis is yet to be \n"
                + "felt.</p>\n"
                + "            <p>In fact 2009 was a good year for most because of lower mortgage rates, the \n"
                + "Rudd Government's two cash splashes, the first-home owner's boost, tax cuts, \n"
                + "falling inflation and the stronger dollar. But the bill will fall due this \n"
                + "year.</p>\n"
                + "            <p>Although it has been widely reported the economy inched ahead at an annual \n"
                + "rate of 0.5 per cent in the September quarter, that is not the full story.</p>\n"
                + "            <p>The truth is there was less to go around per person once you take population \n"
                + "growth into account.</p>\n"
                + "            <h3><b>JOB SEEKERS</b></h3>\n"
                + "            <p>THE unemployment rate is expected to rise because Gross Domestic Product \n"
                + "(GDP) - the value of all the goods and services produced - per head of \n"
                + "population shrank 1.5 per cent over the year, though nowhere near as much as had \n"
                + "been feared. It may even have peaked.</p>\n"
                + "            <p>The Reserve Bank has warned growth in jobs is ''running below growth in the \n"
                + "working-age population''.</p>\n"
                + "            <p>The 2008-09 downturn was unusual as many smaller employers refrained from \n"
                + "shedding staff. They cut hours or wages instead.</p>\n"
                + "            <p>''Businesses were a whole lot smarter than in the past,'' said Craig James, \n"
                + "the chief equities economist at CommSec.</p>\n"
                + "            <p>He predicts ''we'll see greater demand for labour and more hours worked in \n"
                + "2010''.</p>\n"
                + "            <p>The better conditions are also likely to embolden those who held their jobs \n"
                + "to seek a pay rise.</p>\n"
                + "            <p>There are already signs of a thaw.</p>\n"
                + "            <p>On January 1 the Commonwealth Bank lifted the pay freeze it had imposed last \n"
                + "year on senior executives earning more than $100,000 a year.</p>\n"
                + "            <h3><b>SUPER AND INVESTMENTS</b></h3>\n"
                + "            <p>ASSET values are rising.</p>\n"
                + "            <p>Even one of the more pessimistic predictions for the sharemarket, from Chris \n"
                + "Caton of BT Financial Group, is an All Ordinaries Index of 5250 by the end of \n"
                + "this year - an increase of just under 10 per cent.</p>\n"
                + "            <p>Shane Oliver of AMP Capital Investors and Mr James tip the All Ords could \n"
                + "reach 5600, a rise of more than 15 per cent.</p>\n"
                + "            <p>There is good news for investors in bricks and mortar - property prices are \n"
                + "on a roll, despite rising interest rates due to higher immigration and the \n"
                + "housing shortage.</p>\n"
                + "            <p>In the minutes for its December board meeting, the Reserve Bank said building \n"
                + "approvals for houses were ''now well above the lows seen in late 2008'' but for \n"
                + "apartments ''remained around the lowest levels in more than a decade''. Until \n"
                + "construction of units turns around, landlords can expect rising prices and \n"
                + "rents.</p>\n"
                + "            <h3><b>RETIREES</b></h3>\n"
                + "            <p>THE big winners in 2010 could be self-funded retirees and, maybe, even \n"
                + "pensioners.</p>\n"
                + "            <p>A deposit war has flared up between the banks, which are offering term \n"
                + "deposit rates of up to 7 per cent for three years. Even a 12-month deposit, \n"
                + "which would still be government guaranteed, is paying up to 6.8 per cent.</p>\n"
                + "            <p>These are unprecedented returns when compared with either the Reserve Bank's \n"
                + "official cash rate or the rate at which the banks are lending.</p>\n"
                + "            <p>In some cases the banks are paying out more for deposits than they're earning \n"
                + "from the variable mortgage rate, which starts about 6.1 per cent.</p>\n"
                + "            <p>The Reserve Bank is expected to lift rates again, possibly as much as one \n"
                + "percentage point, which would also see term deposits rise.</p>\n"
                + "            <p>There is also strong speculation that Treasury head Ken Henry's review of the \n"
                + "tax system will recommend bank interest be taxed at the same rate as super - 15 \n"
                + "per cent - although it would probably be means tested.</p>\n"
                + "            <p>But financial planners said that any significant reforms from the review are \n"
                + "not likely to be in place until next financial year.</p>\n"
                + "            <p>''You can't anticipate the Henry review. It'll need legislation anyway,'' \n"
                + "said Anne-Marie Esler, technical research manager at Centric Wealth.</p>\n"
                + "            <p>Adding to the returns of self-funded retirees and other savers is the \n"
                + "recovery in the sharemarket, which has clawed back some of the losses of super \n"
                + "funds.</p>\n"
                + "            <p>In 2009 the average super fund was estimated to have returned close to 12 per \n"
                + "cent ''making it one of the best calendar year results this decade'', said Jeff \n"
                + "Bresnahan, managing director of SuperRatings.</p>\n"
                + "            <p>Brokers and fund managers say the next 12 months will be just as good as the \n"
                + "economy picks up.</p>\n"
                + "            <h3><b>HOME BUYERS</b></h3>\n"
                + "            <p>PRESSURE on rents has been intensifying as first-home buyers drop out of the \n"
                + "market because of rising interest rates, cutbacks in the number of hours worked \n"
                + "and the phasing down of the first-home owner's boost.</p>\n"
                + "            <p>Economists were predicting savage falls in home prices when the global \n"
                + "financial crisis hit but most drops turned out to be modest, in part thanks to \n"
                + "restraint on the part of banks, which were desperately avoiding more asset \n"
                + "writedowns.</p>\n"
                + "            <p>Even so, a fundamental shortage of housing is propping up the market.</p>\n"
                + "            <p>''There aren't enough units and apartments. This is causing younger people to \n"
                + "stay at home longer and migrants are having to share,'' said Mr James, who \n"
                + "predicts property prices will rise ''8 to 10 per cent but may be flat in the \n"
                + "early part of 2010''.</p>\n"
                + "            <p>Mortgage holders face rate rises, both from decisions by the Reserve Bank and \n"
                + "the banks acting independently.</p>\n"
                + "            <p>The only bank not to lift rates by more than the Reserve in December, \n"
                + "National Australia Bank, warned ''we expect the overall costs [of funding] to \n"
                + "increase into 2010, driven mainly by the rising average cost of term wholesale \n"
                + "and retail deposit costs''.</p>\n"
                + "            <p>Its cost of deposits rose 1 to 1.2 per cent throughout last year and since \n"
                + "the Reserve Bank lifted rates by 0.75 per cent in that time, the banks must have \n"
                + "at least one more rate rise in the pipeline.</p>\n"
                + "            <h3><b>PENSIONERS </b></h3>\n"
                + "            <p>FOR pensioners the outlook might not be as good as 2009 but it'll still be \n"
                + "one of the better years.</p>\n"
                + "            <p>What they gain on the inflationary swings, such as unseasonably low fresh \n"
                + "food prices, they lose in higher transport and utility charges.</p>\n"
                + "            <p>Pensioners have their own cost of living index compiled by the Australian \n"
                + "Bureau of Statistics. Their returns on bank savings will be better as interest \n"
                + "rates continue to rise.</p>\n"
                + "            <p>''One thing to watch is utility prices. Pensioners will need to factor these \n"
                + "into their budgeting. But in the May budget the Government may identify this \n"
                + "stress,'' Mr James said.</p>\n"
                + "            <h3><b>FAMILIES</b></h3>\n"
                + "            <p>JOE and Jane Average can look forward to a fair to middling year.</p>\n"
                + "            <p>It will be the first July 1 in five years on which there will not have been \n"
                + "any tax cuts.</p>\n"
                + "            <p>Mortgage rates are heading for their long-term norm about 8 per cent.</p>\n"
                + "            <p>Retail prices are forecast by the Reserve Bank to rise by 2.25 per cent this \n"
                + "year, although this will disguise hefty jumps in electricity and public \n"
                + "transport charges.</p>\n"
                + "            <p>But then electronics, clothing and the cost of travel have been falling \n"
                + "thanks to the stronger dollar.</p>\n"
                + "            <p>Many economists are predicting the dollar will hit parity with the Greenback \n"
                + "and the Reserve Bank Governor Glenn Stevens has even suggested $US1.10 was \n"
                + "possible.</p>\n"
                + "            <p>One big unknown is petrol prices.</p>\n"
                + "            <p>These depend on both the cost of crude oil, expected to rise as the global \n"
                + "recovery kicks in, and the dollar's exchange rate with the US dollar.</p>\n"
                + "    </div>\n"
                + "    <!-- articleBody -->\n"
                + "</BOD>\n"
                + "\n"
                             + "\n"
                + "</script>\n"
                + "</div>\n"
                + "\n"
                + "</body>\n"
                + "</html>";
        Document doc = Jsoup.parse(h);
        assertTrue(true);
    }
}
